board: esp32
start:
  must_home: true
stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0
probe:
  pin: gpio.04
  toolsetter_pin: NO_PIN
  check_mode_start: true
  hard_stop: false
kinematics:
  corexy:
axes:
  shared_stepper_disable_pin: gpio.15
  x:
    steps_per_mm: 160
    max_rate_mm_per_min: 15000
    acceleration_mm_per_sec2: 500
    max_travel_mm: 690
    soft_limits: true
    homing:
      cycle: 3
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 500
      seek_mm_per_min: 4000
      settle_ms: 250
    motor0:
      limit_neg_pin: gpio.35:low
      hard_limits: true
      pulloff_mm: 5
      stepstick:
        step_pin: gpio.26
        direction_pin: gpio.25
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
  y:
    steps_per_mm: 160
    max_rate_mm_per_min: 15000
    acceleration_mm_per_sec2: 500
    max_travel_mm: 550
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 500
      seek_mm_per_min: 4000
      settle_ms: 250
    motor0:
      limit_pos_pin: gpio.34:low
      hard_limits: true
      pulloff_mm: 5
      stepstick:
        step_pin: gpio.14
        direction_pin: gpio.27:low
      limit_neg_pin: NO_PIN
      limit_all_pin: NO_PIN
  z:
    steps_per_mm: 1600
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 100
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0
      feed_mm_per_min: 250
      seek_mm_per_min: 500
      settle_ms: 250
    motor0:
      limit_neg_pin: gpio.39:low
      hard_limits: true
      pulloff_mm: 6
      stepstick:
        step_pin: gpio.33
        direction_pin: gpio.32:low
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
  frequency_hz: 10000000
parking:
  enable: true
  axis: Z
  pullout_distance_mm: 5
  pullout_rate_mm_per_min: 250
  target_mpos_mm: -5
  rate_mm_per_min: 800
